### PR TITLE
Enable specifying an Ethereum withdraw address

### PR DESCRIPTION
**Pull request by remyroy**

### CODE REVIEW

**Comment by remyroy** [comment]
Built on top of #129

**Review by colfax23 — COMMENTED** [review]
LGTM!  Nice work, thanks for completing this.  Lets hold it here in this branch until we've done some more testing.

**Comment by remyroy** [comment]
I've completed some more tests and read the related documents on specifying a withdraw address on https://github.com/ethereum/consensus-specs/pull/2149 . You can easily tell if the output of the key gen uses a defined withdraw address by looking at the deposit_data file and the `withdrawal_credentials`. If the value of the `withdrawal_credentials` field starts with `01` followed by a bunch of zeros and the withdraw address, it's because the user who created this key + deposit combo specified a withdraw address. If not, it will start with `00`.

Doing a bunch of tests with this branch and using a withdraw address, I can confirm it has the same behavior as calling the eth2.0-deposit-cli tool with the `--eth1_withdrawal_address` flag.

I think we are good to merge.

**Comment by colfax23** [comment]
Awesome, thanks for doing that.  Two UI things came to mind when testing, can you let me know what you think?

1) I think we should clear the address when we toggle off "Show Advanced Inputs" if there is a value there.  It appears that it stays.
2) When there is an error in one of the top boxes, it shifts the rest of the components down, and it can look messy sometimes.  When I set `alignItems="flex-start"` (it is currently set to `center`, my bad) on the Grid holding the top two components it helped, but the bottom still slides down.  Can you take a look at this?
image

**Comment by remyroy** [comment]
I will look into this. Thanks.

**Comment by remyroy** [comment]
I added code to clear advanced inputs when the toggle is clicked to hide them again.
I added some min-height to fix the fields alignments with error messages.

**Review by colfax23 — APPROVED** [review]
Looks great, signing off. 

Feel free to follow up with changing `Show Advanced Inputs` to `Use Advanced Inputs` if you'd like

**Pull request merged**
