### PR TITLE
Outdated dependencies

### PR DESCRIPTION
**Pull request by remyroy**
Depends on #116 

Move the project to use yarn 2. Updated all packages. Fix some issue with latest version of package and Grid component from material-ui.

### CODE REVIEW

**Review by colfax23 — APPROVED** [review]
LGTM, will test monday as well.

**Comment by colfax23** [comment]
I am getting the following error when running any `yarn` command now:

Error: Cannot find module '/Users/colfaxselby/Documents/projects/stakehouse/wagyu-key-gen/.yarn/releases/yarn-berry.cjs'

Is there a missing file?

**Comment by remyroy** [comment]
Did you try `yarn install` first?

**Comment by colfax23** [comment]
I did, same error.  Will contact you offline to troubleshoot.

**Comment by remyroy** [comment]
The step by step guide to migrate to yarn 2 is in https://yarnpkg.com/getting-started/migration . Maybe you need to perform some of those steps in your environment as well. I'd be happy to try and do some live troubleshooting.

**Comment by colfax23** [comment]
Can you please update the `.gitignore` to reflect the changes specified here? https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

It seems that may be the root cause of the issue.

**Comment by remyroy** [comment]
The gitignore file has been updated.

**Pull request merged**
