### PR TITLE
Make finished folder clickable and open keystore in file manager

### LINKED ISSUE #58: Make key creation folder clickable
The path should be clickable to help users find their keys 

image

### PR DESCRIPTION
**Pull request by remyroy**
Closes #58

### CODE REVIEW

**Comment by colfax23** [comment]
Looks good.  However when clicked, it opens the right folder, but does not select the right file in the folder.  I have some keys from a previous run in that folder and it selected one of the keys from the previous run.  Do you think this will be confusing?  How does it behave for you?

**Comment by remyroy** [comment]
I don't think it will be too confusing. The is mainly to open up the right folder instead of the right file. If you generate multiple keys in the same folder, you should already know what you are doing or we should check that first before generating in that folder to begin with and warn our user.

**Comment by colfax23** [comment]
Makes sense. Is there any way we can just select the folder and no files?

**Comment by remyroy** [comment]
No, not from the native electron shell package at least.

**Review by colfax23 — APPROVED** [review]

**Pull request merged**
