### PR TITLE
Configure electron-builder for executable creation

### PR DESCRIPTION
**Pull request by colfax23**
Implementation for #7 using electron-builder.  Works on Mac and linux.

### CODE REVIEW

**Comment by remyroy** [comment]
Verifying and testing this right now.

**Comment by colfax23** [comment]
@remyroy awesome.  It is not going to work fully yet as the python executable isnt in there yet, but I just got it working locally so will be checking that in soon :)

**Comment by remyroy** [comment]
Bundling the deb package works fine with electron-builder.

It would be nice to add an AppImage target in addition to the deb target so the app can be distributed as some kind of portable app and easily ran on non-debian distros and on distro will limited capacity to install app (Tails with default settings?).

I'll wait full integration to complete the review.

**Comment by colfax23** [comment]
@remyroy it is ready for review now.  Should work fully, let me know any issues.

Agreed on AppImage target, but I had trouble getting the desktop icon to work for AppImage.  Will give it another look.

**Comment by colfax23** [comment]
Created #59 for future AppImage target.

**Pull request closed without merging**
