### PR TITLE
Adding connection detector to alert the user if they are online

### PR DESCRIPTION
**Pull request by valefar-on-discord**
User had a good suggestion to provide a connectivity detection and warning the user: #172 

Adding a listener and using `navigator.onLine` to detect connection while using MUI Snackbar with Alert to display a warning to the user if a connection is detected.

Two UX constraint I added:
 - Added the detection in `App.tsx` so it will exist outside of only the landing component
 - Not being able to dismiss the alert message except through clicking the snackbar action. Closing by clicking away would probably defeat the purpose due to the severity of the security concern.

This can be tested by toggling your wifi connection while the app is open.

### CODE REVIEW

**Comment by remyroy** [comment]
Fixes #172

**Review by remyroy — CHANGES_REQUESTED** [review]
I like the idea. One issue is the size and placement of the warning. It currently hides the main title on all pages.
Screenshot from 2024-01-22 15-13-42

I think a better size and place to avoid hiding the page title, maybe in the top left corner, would be better. Maybe smaller, but it's hard to say if it's still going to be a good experience without trying it first.

My other concern is some people believing they can just temporarily disable networking during their use of the application to be secure when they mostly need to be using an *offline machine* that never was online and never will be. Conveying this idea or this concept in a short sentence is hard in my humble opinion. An *offline machine* is not part of the common techno vocabulary. The current phrase is:

> It is strongly recommended to run this tool offline to avoid exposing your Secret Recovery Phrase

That message could be improved, but I'm not sure how if we want to keep it short. The tooltip on the *offline* word on the home page is:

> You want to avoid exposing your Secret Recovery Phrase to any system that can send it online and compromise your security. Booting from a live OS that does not connect to any network on a USB drive is an easy way to achieve that. You can copy the resulting files on USB drives. You might want to avoid storing your Secret Recovery Phrase electronically.

Arguably, this message could be improved too, but it gives a better idea of the concept.

In the end, we cannot really prevent people from using this in an unsecure way. The addition of a network detector is a good improvement overall.

**Comment by valefar-on-discord** [comment]
Great, great points.

One option that I provided a quick UX example of would be using a Dialog to block the flow and having the user acknowledge with a checkbox, a bit similar to the warning checkboxes launchpad gives when attempting a deposit.

This would provide more real estate for messaging in greater detail as to the issue and provide resources to continue in a more secure manner.

I didn't do any wording yet as I'm not 100% on it yet but wanted to get your thoughts on the UX.

**Comment by remyroy** [comment]
> Great, great points.
> 
> One option that I provided a quick UX example of would be using a Dialog to block the flow and having the user acknowledge with a checkbox, a bit similar to the warning checkboxes launchpad gives when attempting a deposit.
> 
> This would provide more real estate for messaging in greater detail as to the issue and provide resources to continue in a more secure manner.
> 
> I didn't do any wording yet as I'm not 100% on it yet but wanted to get your thoughts on the UX.

I'm guessing this would be an extra step or an extra full page with a big warning that would always be displayed or just when we detect an online connection?

I'm far from being a UX expert, but I think I would dislike the idea of putting an extra *hand-holding* page or dialog that you need to confirm or check everytime you use the app no matter what. I think I would prefer the smaller *always shown unless dismissed* alert in a corner. It's always a compromise in these situations and my preferences can be different from what good UX is.

**Comment by valefar-on-discord** [comment]
> I'm guessing this would be an extra step or an extra full page with a big warning that would always be displayed or just when we detect an online connection?
> 
> I'm far from being a UX expert, but I think I would dislike the idea of putting an extra _hand-holding_ page or dialog that you need to confirm or check everytime you use the app no matter what. I think I would prefer the smaller _always shown unless dismissed_ alert in a corner. It's always a compromise in these situations and my preferences can be different from what good UX is.

The idea was the dialog would only appear if a connection was detected and then closing it would remove the warning permanently.

I've made another update that will show a pulsing connectivity icon in the upper left hand corner if a network connection is detected and clicking on that icon will show a dialog explaining the concern. The user can Close where the dialog will disappear but icon will maintain or "Hide Warning" where the Dialog will close and the icon will disappear as well for the rest of the session.

I'm not 100% on the wording for the dialog but there is plenty of real estate to go into some detail and provide resources to help.

**Review by remyroy — CHANGES_REQUESTED** [review]
I like the new subtle notice and animated pulsating circle. I like the expanded explanation and message about it when you click on the pulsating circle. I like how it does not cover anything else. I think we should add some text in that pulsating circle. Maybe something like *Internet Detected* or just *Warning*. That would be the only remaining change I would make. What do you think?

**Comment by valefar-on-discord** [comment]
> I like the new subtle notice and animated pulsating circle. I like the expanded explanation and message about it when you click on the pulsating circle. I like how it does not cover anything else. I think we should add some text in that pulsating circle. Maybe something like _Internet Detected_ or just _Warning_. That would be the only remaining change I would make. What do you think?

Sounds good to me.

I changed the warning icon to be a button with text and I styled the modal a bit to better match the rest of the application.

**Comment by remyroy** [comment]
Great! Thanks for your great work. Merging.

**Pull request merged**
