### PR TITLE
Added fixed version footer

### PR DESCRIPTION
**Pull request by colfax23**
Screen Shot 2021-11-04 at 6 23 04 PM

### CODE REVIEW

**Comment by colfax23** [comment]
Completes #87

**Review by remyroy — CHANGES_REQUESTED** [review]
It fails to build with a bunch of:

````
TS2307: Cannot find module '../components/VersionFooter' or its corresponding type declarations.
````

Did you forget to add the VersionFooter.tsx file?

**Review by remyroy — CHANGES_REQUESTED** [review]
The footer that includes the version number and the commit hash seems to be moving from step to step. It might just be slightly different or misaligned when you compare the home page to the wizard pages. It seems to jump to the right a little after clicking on the first button.

**Comment by colfax23** [comment]
Good spot.  Fixed.

**Review by remyroy — APPROVED** [review]

**Comment by remyroy** [comment]
Looks good now. Ready to merge.

**Pull request merged**
