### PR TITLE
Cs/error fixes

### PR DESCRIPTION
**Pull request by colfax23**
Fixed all errors.  Some warnings remain.

### CODE REVIEW

**Comment by remyroy** [comment]
I'm getting this warning on application load. Have you seen it? Have you tried to *fix* it?

> Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
> 
> For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.

After verifying the mnemonic using Prater, I'm getting this warning as well:

> (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.

Everything else is fine here.

**Comment by remyroy** [comment]
I see the remote stuff being using to show the *select Folder dialog* on the OS side. Can we use the dialog module instead to fix the related warning? https://www.electronjs.org/docs/latest/api/dialog/

**Comment by colfax23** [comment]
I saw those two warnings, I'll look into the severity of each.

**Comment by remyroy** [comment]
I think the first warning is going to disappear once the application is bundled so maybe that one does not need any work

**Comment by colfax23** [comment]
I believe you are correct.  As for the second warning, I'd like to leave it as is for now and we can investigate later, I created #103 for it.

**Pull request merged**
