### PR TITLE
Add a stepper component

### LINKED ISSUE #3: Progress Bar
Implement a progress bar to signify how far along in the process you are, so the user knows how many steps remain.

### PR DESCRIPTION
**Pull request by rhythnic**
## Why
Stepper component will give the user more assurance of where they are in the sequence of steps.  Fixes #3 

## Design
There are 4 steps in the stepper.  I expect that we'll iterate on the labels displayed.
- Generate/Import Mnemonic
- Configure Keys
- Generate Keys
- Finish

stepper-ui

Within these outer steps, each step may contain sub steps.  Any state that is needed in multiple top-level steps is contained in the MainWizard.  Any other state, like form validation, is contained in within the step.

## Behavioral Changes (besides navigation)
- If the user navigates backwards to the set-password form, the app will remember the password entered previously, but still requires the user to confirm the password again.
- The app defaults to 1 for numberOfKeys to generate.

There are too many changes to list separately, but most changes are refactors for supporting the stepper functionality.
@colfax23 Let me know if you want to meet to discuss the changes.

### CODE REVIEW

**Review by colfax23 — CHANGES_REQUESTED** [review]
This is awesome.  Looks great - better than I had imagined.

A few visual comments:
 - can you boost the footer buttons (back/next) up a bit to even out the spacing from the side, bottom, and progress bar?
 - any way that back from the key configuration page can go back to the last step in the create mnemonic flow?  Rather than the first step?  It's better than it was before, but ideally it would go back to the previous page with the loaded state
 - when you go back from the Config Keys page to the generate or import mnemonic steps, it does not clear state, so when you go forward again to the configure keys page the state is there.  Can you fix this?  Sorry if this is holdover from my earlier implementation.

Open questions:
 - do you think we should add a verify mnemonic page for importing?
 - for new mnemonic, do you think we should start the stepper after the information page?  or leave it as is?

**Comment by rhythnic** [comment]
Sounds good.  I'll be in touch once I've got the changes implemented.  I do think there should be mnemonic import verification.  I don't think the mnemonic generation explanation needs to be removed from the stepper.  We might also consider a mnemonic import explanation that describes the starting index.

**Comment by rhythnic** [comment]
I made the requested changes.  In modifying the network constant to be an enum, I touched the `Eth2Deposit/generateKeys` function.  It needs tested on linux to make sure that the network key is lowercased when it's passed to python.  I would test but I don't have my linux machine with me.

I positioned the buttons more center, and a bit up from the bottom.  There is a bit more space above the buttons than below the buttons to allow for updates and translations to the stepper text, which might be longer.

**Comment by colfax23** [comment]
Awesome, thanks!  Just tried building and running into an error fyi, related to the network enum:

ERROR in /Users/colfaxselby/Documents/projects/stakehouse/wagyu-key-gen/src/react/App.tsx
./src/react/App.tsx 27:80-90
[tsl] ERROR in /Users/colfaxselby/Documents/projects/stakehouse/wagyu-key-gen/src/react/App.tsx(27,81)
      TS2739: Type '{ network: Network; }' is missing the following properties from type 'RouteComponentProps<RouteParams, any, {}>': history, location, match

I'm away from my linux machine as well, but will be able to test this out this weekend.

**Comment by rhythnic** [comment]
@colfax23 I fixed the typescript error

**Comment by colfax23** [comment]
Awesome, thanks @rhythnic.  Just noticed that merging #22 has caused some conflicts here, I need to do a better job of managing issues that touch the same areas of the code.

Once I'm back at my linux machine this weekend I'll give these changes some testing and we can get this merged.  I can help sort out the merge conflicts with #22, most of which are changes just to text so it shouldn't be too bad.

**Comment by rhythnic** [comment]
@colfax23 I fixed the merge conflicts.

**Comment by colfax23** [comment]
@rhythnic awesome, thanks.  Everything looks good, except the 'Back' button is now visible at the final page.  Can you remove that?  I think it is misleading to the user to suggest that going back from there is a suggested flow.  Let me know if you disagree.

Note: added #28 for adding a page to have the user retype their secret recovery phrase.

**Comment by rhythnic** [comment]
@colfax23 I think that's reasonable.  I removed the back button from the finish page.  I forgot to mention, that my PR and Squanch's PR affected most files, so a merge conflict was pretty much unavoidable. I'll try to do smaller PRs in the future, but his one was unavoidable.

**Comment by colfax23** [comment]
Awesome, nice work @rhythnic.  Merged.

**Pull request merged**
