### PR TITLE
Set up storybook and start some changes

### PR DESCRIPTION
**Pull request by colfax23**

### CODE REVIEW

**Comment by colfax23** [comment]
@remyroy Ready now - go for it!

**Comment by remyroy** [comment]
The clicking on the radio button for the Network Picker on Storybook is weird. I have to double click for the radio button to change to my selection. If I single click, it always go back to selecting *Prater (Testnet)*

**Comment by colfax23** [comment]
@remyroy good catch.  Fixed that and properly integrated the picker modal into the Home screen.  I commented out the NetworkPicker story creation as I need to figure out how to pass those params (state handlers), but please review as is.

**Comment by remyroy** [comment]
I just tried the storybook again and it seems to fail: 
failed-storybook
I tried the network switcher in the actual app and it worked fine when trying to switch by clicking on the radio button. It would be nice if we could change the network selection by clicking on the label next to the radio button as well since it require some precision to click on the small radio button.

**Comment by colfax23** [comment]
@remyroy Thanks for the feedback, agreed.  After thinking/playing around with this a bit I've decided to add Material UI to help with some of the components.  Will push an update tomorrow.

Also, for now, storybook for the NetworkPicker is intentionally disabled as I need to work through how to pass the handlers in properly.

**Comment by colfax23** [comment]
Actually, just added material ui now and it looks pretty good.  Please take a look @remyroy and let me know what you think.

**Comment by remyroy** [comment]
Seems good now!

**Pull request merged**
