### PR TITLE
Fixed modal next on click outside of area, also fixed createMuiTheme error

### PR DESCRIPTION
**Pull request by colfax23**

### CODE REVIEW

**Comment by remyroy** [comment]
When I click on outside the network selection modal screen after clicking on the *Create new secret recovery phrase* button, the app still advance.

**Comment by colfax23** [comment]
Good catch.  I missed a file.  The file that actually did the fixing.  Ready for a new test @remyroy - thanks!

**Comment by colfax23** [comment]
Closing as I pushed to main.  Let me know if you find any issues Remy.

**Comment by remyroy** [comment]
Just tested. Seems good.

**Pull request closed without merging**
